default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gameservers_development

test:
  <<: *default
  database: gameservers_test
  
staging:
  <<: *default
  database: gameservers_staging

production:
  <<: *default
  database: gameservers
  
beta:
  <<: *default
  database: deploystation_beta