default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

development:
  <<: *default
  database: deploystation_development

test:
  <<: *default
  database: deploystation_test
  
staging:
  <<: *default
  database: deploystation_staging

beta:
  <<: *default
  database: deploystation_beta
  
production:
  <<: *default
  database: deploystation_production