default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gameservers_development

test:
  <<: *default
  database: gameservers_test
  
staging:
  <<: *default
  database: gameservers_staging

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] || 'deploystation' %>
  username: <%= ENV['RDS_USERNAME'] || 'deploystation' %>
  password: <%= ENV['RDS_PASSWORD'] || 'deploystation' %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  
beta:
  <<: *default
  database: deploystation_beta