default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gameservers_development

test:
  <<: *default
  database: gameservers_test

production:
  <<: *default
  database: gameservers