default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gameservers_development

staging:
  <<: *default
  database: gameservers_staging

production:
  <<: *default
  database: gameservers